### ISSUE TITLE
Add comments to IPYNB and convert to Python Scripts

### ISSUE THREAD

**Issue by achyudh** [achyudhk/Ensemble-Text-Classification#6]
Please remove redundant notebooks, and add comments. Need *PYTHON* scripts for selecting features from matrix and doing cross-val on them. I have scripts for baseline KNN using Chi-Squared, MI crossval and the generation of CF matrix.

**Comment by Shade5** [comment]
@achyudhk Added comments in `feature_selection.ipynb`

**Comment by achyudh** [comment]
Done as of latest commit.
